export const API_URL = 'http://192.168.0.100:3000';
export const API_User = API_URL + '/user/';
export const API_User_Pay = API_URL + '/user/pay/';
export const API_User_Info = API_URL + '/information/';
export const API_Blog = API_URL + '/blog/';
export const API_Product = API_URL + '/product/';
export const API_Type_Product = API_URL + '/product/type/';
export const API_Address = API_URL + '/address/';
export const API_Favorite = API_URL + '/product/favorite/';
